// import localFont from "next/font/local";
// import "./globals.css";
"use client"
import { usePathname } from "next/navigation";
import PageHome from "./page";
import UserProvider from "./contexts/UserProvider";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import Menu from "@/app/components/Menu"
export default function RootLayout({ children }) {
  const pathName = usePathname() // login / profile
  return (
    <html lang="en">
      <body
        className="">
        <UserProvider>
          {pathName != "/login" ? <Menu /> : null}

          {children}
        </UserProvider>
      </body>
    </html>
  );
}
